apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: pokfinner/result:latest
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_HOST
          value: "db"
