apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: pokfinner/vote:latest
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "redis"
