name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
  run: |
    docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest -f ./vote/Dockerfile ./vote
    docker push ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest

    docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/result:latest -f ./result/Dockerfile ./result
    docker push ${{ secrets.DOCKERHUB_USERNAME }}/result:latest

    docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest -f ./worker/Dockerfile ./worker
    docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Update kubeconfig
        run: eksctl utils write-kubeconfig --cluster ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Apply Kubernetes manifests
        run: kubectl apply -f K8s/
